version: "3.8"

services:
  app:
    build: .
    container_name: pyweb
    ports:
      - "80:80"
    volumes:
      - ./src:/code/src
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/pyweb
      - RELOAD=true
      - SECRET_KEY=B01D81075A17B5BE4ACA9DA369E556FF
      - ALGORITHM=HS256
      - TOKEN_EXPIRE_TIME=15
  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pyweb
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: