version: "3.8"

services:
  app:
    build: .
    container_name: pyweb
    command: /code/.venv/bin/uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "80:80"
    volumes:
      - ./src:/code/src
