version: "3.8"

services:
  app:
    build: .
    container_name: pyweb
    ports:
      - "80:80"
    volumes:
      - ./src:/code/src
      - ./bucket:/code/bucket
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/attempt
      - RELOAD=true
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - TOKEN_EXPIRE_TIME=${TOKEN_EXPIRE_TIME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "3254:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=attempt
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: