on: [push]
env:
  DATABASE_URL: postgresql+psycopg://postgres:postgres@127.0.0.1:3254/test
  SECRET_KEY: 306456ef543dca447c4e6eee7c2c7ced5298330e15d107d3435c4e25eba5e54f
  ALGORITHM: HS256
  TOKEN_EXPIRE_TIME: 20
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 3254:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==1.7.1
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - name: Run migrations
        run: poetry run alembic upgrade head
      - name: Lint
        run: make lint-ci
      - name: Test
        run: make test