on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-interaction --no-ans
      - name: Lint
        run: make lint
      - name: Test
        run: pytest